name: neo4j_dart
description: >
  A Neo4j driver for Dart.
version: 0.3.2
author: Rasmus Eneman <rasmus@eneman.eu>
homepage: https://github.com/Pajn/Neo4jDart
dependencies:
  crypto: ^2.1.4
  http: ^0.12.0+4
  quiver: ^2.1.3
  uuid: ^2.0.4
#  warehouse: ">=0.1.2 <0.2.0"
environment:
  # Works in 2.1 but not 2.0.
  sdk: '>=2.1.0 <3.0.0'
